# Generated by Django 2.2.4 on 2019-08-13 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_author'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'author')},
        ),
    ]
